trigger:
  - working

pool:
  name: Agent

steps:
  - task: Docker@2
    displayName: 'Login to ACR'
    inputs:
      command: login
      containerRegistry: 'DemoServConn'

  - script: |
      docker build -t demodevopsregistry.azurecr.io/demo_app:latest .
      docker push demodevopsregistry.azurecr.io/demo_app:latest
    displayName: 'Build and Push'

  - script: |
      docker pull demodevopsregistry.azurecr.io/demo_app:latest
    displayName: 'Pull Latest Image'

  - script: |
      docker run -d -p 8091:8080 demodevopsregistry.azurecr.io/demo_app:latest
    displayName: 'Run Latest Image'
